apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-repo
  namespace: kargo-advanced
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ${GITOPS_REPO_URL}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}

---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: bluebird-dev
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: red
spec:
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: main
      kustomize:
        images:
        - image: docker.io/davittorchyan/kargo:v1.0
          path: stages/test
    argoCDAppUpdates:
    - appName: bluebird-dev
      appNamespace: argocd-apps
  requestedFreight:
    - origin:
        kind: Warehouse
        name: bluebird
      sources:
        direct: true

---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: bluebird-staging
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: amber
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  requestedFreight:
    - origin:
        kind: Warehouse
        name: bluebird
      sources:
        stages:
        - dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: main
      kustomize:
        images:
        - image: docker.io/davittorchyan/kargo:v1.0
          path: stages/staging
    argoCDAppUpdates:
    - appName: bluebird-staging
      appNamespace: argocd-apps

---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: ab-test-a
#   namespace: kargo-advanced
#   annotations:
#     kargo.akuity.io/color: yellow
# spec:
#   subscriptions:
#     upstreamStages:
#       - name: staging
#   requestedFreight:
#     - origin:
#         kind: Warehouse
#         name: guestbook
#       sources:
#         stages:
#         - staging
#   verification:
#     analysisTemplates:
#     - name: cat-fact

---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: ab-test-b
#   namespace: kargo-advanced
#   annotations:
#     kargo.akuity.io/color: green
# spec:
#   subscriptions:
#     upstreamStages:
#       - name: staging
#   requestedFreight:
#     - origin:
#         kind: Warehouse
#         name: guestbook
#       sources:
#         stages:
#         - staging
#   verification:
#     analysisTemplates:
#     - name: cat-fact-fail

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: blue
spec:
  subscriptions:
    upstreamStages:
      - name: staging
  requestedFreight:
    - origin:
        kind: Warehouse
        name: bluebird
      sources:
        stages:
        - staging

---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: bluebird-prod-west
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-west
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  requestedFreight:
    - origin:
        kind: Warehouse
        name: bluebird
      sources:
        stages:
        - prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: main
      kustomize:
        images:
        - image: docker.io/davittorchyan/kargo:v1.0
          path: stages/prod-west
    argoCDAppUpdates:
    - appName: bluebird-prod-west
      appNamespace: argocd-apps

---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: bluebird-prod-central
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-central
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  requestedFreight:
    - origin:
        kind: Warehouse
        name: bluebird
      sources:
        stages:
        - prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: main
      kustomize:
        images:
        - image: docker.io/davittorchyan/kargo:v1.0
          path: stages/prod-central
    argoCDAppUpdates:
    - appName: bluebird-prod-central
      appNamespace: argocd-apps

---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: bluebird-prod-east
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-east
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  requestedFreight:
    - origin:
        kind: Warehouse
        name: bluebird
      sources:
        stages:
        - prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: main
      kustomize:
        images:
        - image: docker.io/davittorchyan/kargo:v1.0
          path: stages/prod-east
    argoCDAppUpdates:
    - appName: bluebird-prod-east
      appNamespace: argocd-apps
