apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-repo
  namespace: kargo-advanced
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ${GITOPS_REPO_URL}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: red
spec:
  # subscriptions:
  #   warehouse: guestbook
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: env/dev
      kustomize:
        images:
        - image: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
          path: stages/test
    argoCDAppUpdates:
    - appName: guestbook
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: true
      # gitRepoUpdates:
      #   repoURL: https://github.com/davittorch/bluebird-kargo.git
      #   writeBranch: env/dev
      #   render: {}
      # argoCDAppUpdates:
      #   appName: guestbook-dev
  # promotionMechanisms:
  #   gitRepoUpdates:
  #   - repoURL: https://github.com/davittorch/bluebird-kargo.git
  #     writeBranch: env/dev
  #     render: {}
  #   argoCDAppUpdates:
  #   - appName: guestbook

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: amber
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
        - dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: env/staging
      kustomize:
        images:
        - image: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
          path: stages/staging
    argoCDAppUpdates:
    - appName: guestbook

---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: ab-test-a
#   namespace: kargo-advanced
#   annotations:
#     kargo.akuity.io/color: yellow
# spec:
#   subscriptions:
#     upstreamStages:
#       - name: staging
#   requestedFreight:
#     - origin:
#         kind: Warehouse
#         name: guestbook
#       sources:
#         stages:
#         - staging
#   verification:
#     analysisTemplates:
#     - name: cat-fact

---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: ab-test-b
#   namespace: kargo-advanced
#   annotations:
#     kargo.akuity.io/color: green
# spec:
#   subscriptions:
#     upstreamStages:
#       - name: staging
#   requestedFreight:
#     - origin:
#         kind: Warehouse
#         name: guestbook
#       sources:
#         stages:
#         - staging
#   verification:
#     analysisTemplates:
#     - name: cat-fact-fail

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: blue
spec:
  subscriptions:
    upstreamStages:
      - name: staging
      # - name: ab-test-a
      # - name: ab-test-b
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
        - staging
  # promotionMechanisms:
  #   gitRepoUpdates:
  #   - repoURL: https://github.com/davittorch/bluebird-kargo.git
  #     writeBranch: env/prod
  #     render: {}
  #   argoCDAppUpdates:
  #   - appName: guestbook

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-west
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
        - prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: env/prod-west
      kustomize:
        images:
        - image: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
          path: stages/prod-west
    argoCDAppUpdates:
    - appName: guestbook

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-central
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
        - prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: env/prod-central
      kustomize:
        images:
        - image: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
          path: stages/prod-central
    argoCDAppUpdates:
    - appName: guestbook

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-east
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
        - prod
      # gitRepoUpdates:
      #   repoURL: https://github.com/davittorch/bluebird-kargo.git
      #   writeBranch: env/prod-east
      #   render: {}
      # argoCDAppUpdates:
      #   appName: guestbook-prod-east
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/davittorch/bluebird-kargo.git
      writeBranch: env/prod-east
      kustomize:
        images:
        - image: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
          path: stages/prod-east
    argoCDAppUpdates:
    - appName: guestbook
