apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: bluebird
  namespace: kargo-advanced
spec:
  freightCreationPolicy: Automatic
  interval: "1m0s"
  subscriptions:
  - image:
      repoURL: davittorchyan/kargo
      imageSelectionStrategy: SemVer
      allowTags: ^v?[0-9]+\.[0-9]+(\.[0-9]+)?([\+-].*)?$
  - git:
      repoURL: https://davittorch@github.com/davittorch/bluebird-kargo.git
      branch: main
