apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-advanced
spec:
  subscriptions:
  - image:
      repoURL: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
      imageSelectionStrategy: SemVer
      allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
  - git:
      repoURL: https://github.com/akuity/kargo-advanced.git
      branch: main
