apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-advanced
spec:
  freightCreationPolicy: Automatic
  interval: "1m0s"
  subscriptions:
  - image:
      repoURL: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird
      imageSelectionStrategy: SemVer
      allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
  - git:
      repoURL: https://github.com/davittorch/bluebird-kargo.git
      branch: main
