apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
  - patch-deployment-name.yaml

# namespace: argocd-apps
# clusterSecretStore.namespace: argocd-apps
# externalSecret.namespace: argocd-apps
