apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluebird-chart
  namespace: bluebird
  labels:
    app: bluebird-chart
spec:
  selector:
    matchLabels:
      app: bluebird-chart
  template:
    metadata:
      labels:
        app: bluebird-chart
    spec:
      serviceAccountName: aws-secrets-access
      containers:
        - name: bluebird-chart
          imagePullPolicy: always
          image: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
          resources:
            requests:
              memory: "50Mi"
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: rds-credentials-k8s
                  key: host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-credentials-k8s
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-credentials-k8s
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-credentials-k8s 
                  key: dbname
          ports:
            - containerPort: 80
      tolerations:
        - operator: "Exists"