apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bluebird-chart.fullname" . }}
  namespace: bluebird
  labels:
    app: {{ include "bluebird-chart.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: dev-service
                port:
                  number: 80
          - path: /staging
            pathType: Prefix
            backend:
              service:
                name: staging-service
                port:
                  number: 80
          - path: /prod
            pathType: Prefix
            backend:
              service:
                name: prod-service
                port:
                  number: 80

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "bluebird-chart.fullname" . }}
#   namespace: bluebird
#   labels:
#     app: {{ include "bluebird-chart.name" . }}
# spec:
#   rules:
#     - host: {{ .Values.ingress.host }}
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ include "bluebird-chart.fullname" . }}
#                 port:
#                   number: 80