apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluebird-dev-bluebird-chart
  namespace: bluebird
  labels:
    app: "bluebird-chart"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "ab2ac14d113d44fbca1e001dc101ee7f-d7c31ee35d87ae02.elb.us-east-1.amazonaws.com"
      http:
        paths:
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: dev-service
                port:
                  number: 80


# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: bluebird-staging-bluebird-chart
#   namespace: bluebird
#   labels:
#     app: {{ include "bluebird-chart.name" . }}
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: "nginx"
# spec:
#   rules:
#     - host: {{ .Values.ingress.host }}
#       http:
#         paths:
#           - path: /staging
#             pathType: Prefix
#             backend:
#               service:
#                 name: staging-service
#                 port:
#                   number: 80


# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: bluebird-prod-bluebird-chart
#   namespace: bluebird
#   labels:
#     app: {{ include "bluebird-chart.name" . }}
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: "nginx"
# spec:
#   rules:
#     - host: {{ .Values.ingress.host }}
#       http:
#         paths:
#           - path: /prod
#             pathType: Prefix
#             backend:
#               service:
#                 name: prod-service
#                 port:
#                   number: 80


# ---------------------------------------------------------------------------------------




# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "bluebird-chart.fullname" . }}
#   namespace: bluebird
#   labels:
#     app: {{ include "bluebird-chart.name" . }}
# spec:
#   rules:
#     - host: {{ .Values.ingress.host }}
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ include "bluebird-chart.fullname" . }}
#                 port:
#                   number: 80