apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Ingress
    name: bluebird-dev-bluebird-chart
  patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /dev



# patchesStrategicMerge:
#   - patch-deployment-name.yaml

# namespace: argocd-apps
# clusterSecretStore.namespace: argocd-apps
# externalSecret.namespace: argocd-apps