apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bluebird
  namespace: argocd-apps
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: external-secrets.io
    kind: ClusterSecretStore
  destinations:
  - namespace: argocd-apps
    server: '*'
  - name: '*'
    namespace: bluebird*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/davittorch/bluebird-kargo.git
