apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bluebird
  namespace: argocd-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/davittorch/bluebird-kargo.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: bluebird-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-advanced:*
    spec:
      destination:
        namespace: bluebird-{{path.basename}}
        server: https://kubernetes.default.svc
      project: bluebird
      source:
        path: base/apps
        repoURL: https://github.com/davittorch/bluebird-kargo.git
        targetRevision: main
