apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: 211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird:v1.0
        name: guestbook
        ports:
        - name: http
          containerPort: 3000