apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bluebird

resources:
- ./apps/templates/cluster-secrets-store.yaml
- ./apps/templates/deployment.yaml
- ./apps/templates/external-secret.yaml
- ./apps/templates/ingress.yaml
- ./apps/templates/keda.yaml
- ./apps/templates/service.yaml