apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook

resources:
- guestbook-ns.yaml
- guestbook-deploy.yaml
- guestbook-svc.yaml
- ./apps/templates/cluster-secrets-store.yaml
- ./apps/templates/deployment.yaml
- ./apps/templates/external-secret.yaml
- ./apps/templates/ingress.yaml
- ./apps/templates/keda.yaml
- ./apps/templates/service.yaml