apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - path: patch-deployment-name.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: bluebird-dev-bluebird-chart


# patchesStrategicMerge:
#   - patch-deployment-name.yaml

# namespace: argocd-apps
# clusterSecretStore.namespace: argocd-apps
# externalSecret.namespace: argocd-apps